<a href="https://colab.research.google.com/github/Venky404/Google-Colab-Assignment/blob/main/Assign23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Setup, Load Dataset & Preprocessing

In [12]:
# Import required libraries

import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    r2_score,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [13]:
uploaded = files.upload()

Saving Most Streamed Artists on Spotify (17_07_2026) V1.1.csv to Most Streamed Artists on Spotify (17_07_2026) V1.1 (1).csv

In [14]:
df = pd.read_csv("Most Streamed Artists on Spotify (17_07_2026) V1.1.csv")

df.head()

,Artist Name,Sex,Country of Origin,Primary Language,Primary Genre,Artist Type,Debut Year,Total Streams (in millions),Lead Streams (in millions),Feature Streams (in millions),Solo Streams (in millions),% of Solo Streams,Collaborative Streams (in millions),% of Collaborative Streams
0,Drake,Male,Canada,English,Hip-Hop,Solo,2006,137492.1,94851.1,42640.9,53323.9,38.783246,84168.2,61.216754
1,Taylor Swift,Female,United States,English,Pop,Solo,2006,127861.0,126177.3,1683.8,113421.5,88.706877,14439.5,11.293123
2,Bad Bunny,Male,United States,Spanish,Reggaeton,Solo,2013,125899.8,82189.3,43710.5,48887.0,38.830086,77012.8,61.169914
3,The Weeknd,Male,Canada,English,R&B,Solo,2009,95703.2,77189.4,18513.8,51020.0,53.310652,44683.2,46.689348
4,Justin Bieber,Male,Canada,English,Pop,Solo,2009,78104.4,48316.2,29788.2,29638.3,37.947030,48466.1,62.052970

In [15]:
print("Dataset Shape :", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape : (500, 14)

Column Names:
['Artist Name', 'Sex', 'Country of Origin', 'Primary Language', 'Primary Genre', ' Artist Type', 'Debut Year', 'Total Streams (in millions)', 'Lead Streams (in millions)', 'Feature Streams (in millions)', 'Solo Streams (in millions)', '% of Solo Streams', 'Collaborative Streams (in millions)', '% of Collaborative Streams']

Missing Values:
Artist Name                            0
Sex                                    0
Country of Origin                      0
Primary Language                       0
Primary Genre                          0
 Artist Type                           0
Debut Year                             0
Total Streams (in millions)            0
Lead Streams (in millions)             0
Feature Streams (in millions)          0
Solo Streams (in millions)             0
% of Solo Streams                      0
Collaborative Streams (in millions)    0
% of Collaborative Streams             0
dtype: int64

In [16]:
median_streams = df["Total Streams (in millions)"].median()

df["Popularity"] = np.where(
    df["Total Streams (in millions)"] >= median_streams,
    1,
    0
)

df[["Total Streams (in millions)", "Popularity"]].head()

   Total Streams (in millions)  Popularity
0                     137492.1           1
1                     127861.0           1
2                     125899.8           1
3                      95703.2           1
4                      78104.4           1

In [17]:
# Regression Target (Q1)

X_reg = df.drop(columns=["Total Streams (in millions)", "Popularity"])

y_reg = df["Total Streams (in millions)"]

# Classification Target (Q2,Q3,Q4,Q5)

X_cls = df.drop(columns=["Total Streams (in millions)", "Popularity"])

y_cls = df["Popularity"]

In [18]:
numerical_columns = X_cls.select_dtypes(
    include=["int64", "float64"]
).columns

categorical_columns = X_cls.select_dtypes(
    include=["object"]
).columns

In [25]:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numerical_columns),
    ("cat", categorical_transformer, categorical_columns)
])

In [26]:
# Linear Regression

X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.20,
    random_state=42
)

# Classification Models

X_train_cls, X_test_cls, y_train_cls, y_test_cls = train_test_split(
    X_cls,
    y_cls,
    test_size=0.20,
    random_state=42
)

In [27]:
# Linear Regression

X_train_reg = preprocessor.fit_transform(X_train_reg)
X_test_reg = preprocessor.transform(X_test_reg)

# Classification Models

X_train_cls = preprocessor.fit_transform(X_train_cls)
X_test_cls = preprocessor.transform(X_test_cls)

# Dense arrays for Naive Bayes

X_train_cls_dense = X_train_cls.toarray()
X_test_cls_dense = X_test_cls.toarray()

print("Preprocessing completed successfully.")

Preprocessing completed successfully.

Q1. Linear Regression

In [28]:
# Train Linear Regression Model

linear_model = LinearRegression()

linear_model.fit(X_train_reg, y_train_reg)

LinearRegression()

In [29]:
# Predict the test data

y_pred_reg = linear_model.predict(X_test_reg)

In [30]:
# Calculate R² Score

r2 = r2_score(y_test_reg, y_pred_reg)

print("R² Score :", round(r2, 4))

R² Score : 1.0

In [31]:
# Compare Actual and Predicted Values

prediction_df = pd.DataFrame({
    "Actual Streams": y_test_reg.values,
    "Predicted Streams": y_pred_reg
})

prediction_df.head(10)

   Actual Streams  Predicted Streams
0          8965.0        8990.827772
1         25875.8       25864.953418
2          8779.9        8792.485699
3         15775.7       15779.275447
4         19830.5       19836.501905
5          8439.5        8436.257468
6          8706.4        8731.817386
7         18064.3       18066.960261
8         27406.8       27393.420219
9          7645.2        7673.435236

In [32]:
print("Q1 Completed Successfully")
print("The Linear Regression model was trained.")
print("The model was evaluated using the R² Score.")

Q1 Completed Successfully
The Linear Regression model was trained.
The model was evaluated using the R² Score.

Q2. Logistic Regression

In [33]:
# Train Logistic Regression Model

logistic_model = LogisticRegression(max_iter=1000)

logistic_model.fit(X_train_cls, y_train_cls)

LogisticRegression(max_iter=1000)

In [34]:
# Predict the test data

y_pred_log = logistic_model.predict(X_test_cls)

In [35]:
cm = confusion_matrix(y_test_cls, y_pred_log)

print("Confusion Matrix")
print(cm)

Confusion Matrix
[[54  0]
 [ 1 45]]

In [36]:
accuracy = accuracy_score(y_test_cls, y_pred_log)

precision = precision_score(y_test_cls, y_pred_log)

recall = recall_score(y_test_cls, y_pred_log)

f1 = f1_score(y_test_cls, y_pred_log)

print("Accuracy :", round(accuracy,4))
print("Precision:", round(precision,4))
print("Recall   :", round(recall,4))
print("F1 Score :", round(f1,4))

Accuracy : 0.99
Precision: 1.0
Recall   : 0.9783
F1 Score : 0.989

In [37]:
print(classification_report(y_test_cls, y_pred_log))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        54
           1       1.00      0.98      0.99        46

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

In [38]:
print("Q2 Completed Successfully")
print("The Logistic Regression model was trained.")
print("The model was evaluated using:")
print("- Confusion Matrix")
print("- Accuracy")
print("- Precision")
print("- Recall")
print("- F1 Score")

Q2 Completed Successfully
The Logistic Regression model was trained.
The model was evaluated using:
- Confusion Matrix
- Accuracy
- Precision
- Recall
- F1 Score

Q3. K-Nearest Neighbors (KNN)

In [39]:
# Train KNN models with different K values

k_values = [3, 5, 7]
accuracy_list = []

for k in k_values:
    knn_model = KNeighborsClassifier(n_neighbors=k)

    knn_model.fit(X_train_cls, y_train_cls)

    y_pred_knn = knn_model.predict(X_test_cls)

    accuracy = accuracy_score(y_test_cls, y_pred_knn)

    accuracy_list.append(accuracy)

    print(f"K = {k} --> Accuracy = {accuracy:.4f}")

K = 3 --> Accuracy = 0.8900
K = 5 --> Accuracy = 0.8700
K = 7 --> Accuracy = 0.8900

In [40]:
# Compare accuracy of different K values

knn_results = pd.DataFrame({
    "K Value": k_values,
    "Accuracy": accuracy_list
})

knn_results

   K Value  Accuracy
0        3      0.89
1        5      0.87
2        7      0.89

In [41]:
best_accuracy = max(accuracy_list)
best_k = k_values[accuracy_list.index(best_accuracy)]

print("Best K Value :", best_k)
print("Best Accuracy :", round(best_accuracy, 4))

Best K Value : 3
Best Accuracy : 0.89

In [42]:
print("Q3 Completed Successfully")
print("The KNN model was trained with K = 3, 5, and 7.")
print("The model with the highest accuracy was selected as the best.")

Q3 Completed Successfully
The KNN model was trained with K = 3, 5, and 7.
The model with the highest accuracy was selected as the best.

Q4. Naive Bayes

In [43]:
# Train Gaussian Naive Bayes Model

naive_model = GaussianNB()

naive_model.fit(X_train_cls_dense, y_train_cls)

GaussianNB()

In [44]:
# Predict test data

y_pred_nb = naive_model.predict(X_test_cls_dense)

In [45]:
cm_nb = confusion_matrix(y_test_cls, y_pred_nb)

print("Confusion Matrix")
print(cm_nb)

Confusion Matrix
[[14 40]
 [ 1 45]]

In [46]:
print(classification_report(y_test_cls, y_pred_nb))

              precision    recall  f1-score   support

           0       0.93      0.26      0.41        54
           1       0.53      0.98      0.69        46

    accuracy                           0.59       100
   macro avg       0.73      0.62      0.55       100
weighted avg       0.75      0.59      0.54       100

In [47]:
accuracy_nb = accuracy_score(y_test_cls, y_pred_nb)

print("Accuracy :", round(accuracy_nb, 4))

Accuracy : 0.59

In [48]:
print("Q4 Completed Successfully")
print("The Gaussian Naive Bayes model was trained.")
print("The model was evaluated using the Confusion Matrix,")
print("Classification Report, and Accuracy.")

Q4 Completed Successfully
The Gaussian Naive Bayes model was trained.
The model was evaluated using the Confusion Matrix,
Classification Report, and Accuracy.

Q5: Algorithm Comparison

In [49]:
# Logistic Regression Metrics

log_accuracy = accuracy_score(y_test_cls, y_pred_log)
log_precision = precision_score(y_test_cls, y_pred_log)
log_recall = recall_score(y_test_cls, y_pred_log)
log_f1 = f1_score(y_test_cls, y_pred_log)

In [50]:
# Train KNN using the best K value

best_knn = KNeighborsClassifier(n_neighbors=best_k)

best_knn.fit(X_train_cls, y_train_cls)

y_pred_knn = best_knn.predict(X_test_cls)

knn_accuracy = accuracy_score(y_test_cls, y_pred_knn)
knn_precision = precision_score(y_test_cls, y_pred_knn)
knn_recall = recall_score(y_test_cls, y_pred_knn)
knn_f1 = f1_score(y_test_cls, y_pred_knn)

In [51]:
# Naive Bayes Metrics

nb_accuracy = accuracy_score(y_test_cls, y_pred_nb)
nb_precision = precision_score(y_test_cls, y_pred_nb)
nb_recall = recall_score(y_test_cls, y_pred_nb)
nb_f1 = f1_score(y_test_cls, y_pred_nb)

In [52]:
comparison = pd.DataFrame({

    "Algorithm":[
        "Logistic Regression",
        "K-Nearest Neighbors",
        "Naive Bayes"
    ],

    "Accuracy":[
        log_accuracy,
        knn_accuracy,
        nb_accuracy
    ],

    "Precision":[
        log_precision,
        knn_precision,
        nb_precision
    ],

    "Recall":[
        log_recall,
        knn_recall,
        nb_recall
    ],

    "F1 Score":[
        log_f1,
        knn_f1,
        nb_f1
    ]

})

comparison

             Algorithm  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression      0.99   1.000000  0.978261  0.989011
1  K-Nearest Neighbors      0.89   0.872340  0.891304  0.881720
2          Naive Bayes      0.59   0.529412  0.978261  0.687023

In [53]:
best_model = comparison.loc[comparison["Accuracy"].idxmax()]

print("Best Performing Algorithm")
print("----------------------------")
print(best_model)

Best Performing Algorithm
----------------------------
Algorithm    Logistic Regression
Accuracy                    0.99
Precision                    1.0
Recall                  0.978261
F1 Score                0.989011
Name: 0, dtype: object

In [54]:
print("Assignment Conclusion")
print("--------------------------------------------------")
print("Three classification algorithms were implemented:")
print("1. Logistic Regression")
print("2. K-Nearest Neighbors (KNN)")
print("3. Naive Bayes")
print()

print("The models were compared using:")
print("- Accuracy")
print("- Precision")
print("- Recall")
print("- F1 Score")
print()

print("The algorithm with the highest Accuracy was selected as the best-performing model for this dataset.")

Assignment Conclusion
--------------------------------------------------
Three classification algorithms were implemented:
1. Logistic Regression
2. K-Nearest Neighbors (KNN)
3. Naive Bayes

The models were compared using:
- Accuracy
- Precision
- Recall
- F1 Score

The algorithm with the highest Accuracy was selected as the best-performing model for this dataset.